type LaunchesTypes = {
  FETCH_LAUNCHES_REQUEST: string,
  FETCH_LAUNCHES_SUCCESS: string,
  FETCH_LAUNCHES_FAILURE: string,
  INCREMENT_INDEXES: string,
  SET_NO_MORE_DATA: string,
}

export const launchesTypes: LaunchesTypes = {
  FETCH_LAUNCHES_REQUEST: 'FETCH_LAUNCHES_REQUEST',
  FETCH_LAUNCHES_SUCCESS: 'FETCH_LAUNCHES_SUCCESS',
  FETCH_LAUNCHES_FAILURE: 'FETCH_LAUNCHES_FAILURE',
  INCREMENT_INDEXES: 'INCREMENT_INDEXES',
  SET_NO_MORE_DATA: 'SET_NO_MORE_DATA',
}

